---
abstract: "SHARYANTO's temporary namespace for various routines"
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::Exception: 0
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SHARYANTO-Utils
recommends:
  Term::Size: 0
requires:
  Color::ANSI::Util: 0.03
  Data::Clone: 0
  File::Slurp: 0
  File::Which: 0
  HTML::Parser: 0
  Locale::Maketext::Lexicon: 0
  Log::Any: 0
  Module::List: 0
  Moo::Role: 0
  Parse::Netstat: 0
  Perinci::Object: 0.07
  Rinci: v1.1.0
  Template::Tiny: 0
  Term::Detect::Software: 0
  URI::URL: 0
  experimental: 0
  perl: 5.010001
resources:
  homepage: http://search.cpan.org/dist/SHARYANTO-Utils/
  repository: http://github.com/sharyanto/perl-SHARYANTO-Utils
version: 0.59
